version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: image-classification-api
    container_name: image-classification-api
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./data:/app/data
      - ./temp:/app/temp
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=${MODEL_PATH:-checkpoints/20250123_124210/best_model.onnx}
      - CLASS_MAPPING_PATH=${CLASS_MAPPING_PATH:-data/class_mapping.json}
      - MAX_WORKERS=4
      - WORKERS_PER_CORE=1
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    restart: unless-stopped
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge